apiVersion: v1
kind: Secret
metadata:
  name: staff-tests-repository-tests-job
  labels:
    app: job
    name: staff-tests-repository-tests-job
type: Opaque
data:
  BACKSTAGE_CLIENT_SECRET: {{BACKSTAGE_AZURE_CLIENT_SECRET}}
  BACKSTAGE_PASSWORD: {{SA_BACKSTAGE_USER_PASSWORD}}
