apiVersion: v1
kind: ConfigMap
metadata:
  name: staff-tests-repository-tests-job
  labels:
    app: job
    name: staff-tests-repository-tests-job
data:
  STAFF_CATALOG_URL: {{STAFF_CATALOG_URL}}
  ENV_SHORT_NAME: {{ENV_SHORT_NAME}}
  STAFF_REPORT_PORTAL_URL: {{STAFF_REPORT_PORTAL_URL}}
  STAFF_REPORT_PORTAL_UUID: {{STAFF_REPORT_PORTAL_UUID}}
  STAFF_CATALOG_API_TOKEN: {{STAFF_CATALOG_API_TOKEN}}
  BROWSERSTACK_USERNAME: {{BROWSERSTACK_USERNAME}}
  BROWSERSTACK_ACCESS_KEY: {{BROWSERSTACK_ACCESS_KEY}}
  BACKSTAGE_USERNAME: {{SA_BACKSTAGE_USER}}
  BACKSTAGE_CLIENT_ID: {{BACKSTAGE_AZURE_CLIENT_ID}}
  BACKSTAGE_TENANT_ID: {{AZURE_TENANT_ID}}
  BACKSTAGE_GRANT_TYPE: {{SA_BACKSTAGE_GRANT_TYPE}}
